name: CI

on:
  push:
    branches: ["**"]
  pull_request:

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  # ---------- FRONT: tests + coverage -> ARTIFACTS ----------
  front-tests:
    name: Front tests & coverage (artifact)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: npm
          cache-dependency-path: front/package-lock.json

      - run: npm ci
      - run: npm run build --if-present
      - name: Test (headless) + coverage
        run: npm run test:ci -- --code-coverage

      # Sanity check pour éviter un artifact vide
      - name: Check LCOV exists
        run: |
          test -f coverage/bobapp/lcov.info || {
            echo "::error::front coverage manquante"; ls -R coverage || true; exit 1; }

      - name: Upload test results (Front)
        uses: actions/upload-artifact@v4
        with:
          name: test-results-front
          path: front/reports/**/*.xml
          if-no-files-found: error

      - name: Upload coverage (Front)
        uses: actions/upload-artifact@v4
        with:
          name: coverage-front
          path: front/coverage/**
          if-no-files-found: error

  # ---------- BACK: tests + JaCoCo -> ARTIFACTS ----------
  back-tests:
    name: Back tests & coverage (artifact)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Maven verify (tests + JaCoCo)
        run: mvn -B clean verify

      # Sanity check pour éviter un artifact vide
      - name: Check JaCoCo XML exists
        run: |
          test -f target/site/jacoco/jacoco.xml || {
            echo "::error::jacoco.xml manquant"; ls -R target/site || true; exit 1; }

      - name: Upload test results (Back)
        uses: actions/upload-artifact@v4
        with:
          name: test-results-back
          path: back/target/surefire-reports/*.xml
          if-no-files-found: error

      - name: Upload coverage (Back)
        uses: actions/upload-artifact@v4
        with:
          name: coverage-back
          path: back/target/site/jacoco/**
          if-no-files-found: error

  # ---------- REPORTS (affichage JUnit) ----------
  report-tests:
    name: Test Reports (from artifacts)
    runs-on: ubuntu-latest
    needs: [front-tests, back-tests]
    if: success() || failure()
    steps:
      - name: Report Front (JUnit)
        uses: phoenix-actions/test-reporting@v15
        with:
          artifact: test-results-front
          name: "Front - Karma/Jasmine"
          path: "**/*.xml"
          reporter: "java-junit"

      - name: Report Back (JUnit)
        uses: phoenix-actions/test-reporting@v15
        with:
          artifact: test-results-back
          name: "Back - JUnit"
          path: "*.xml"
          reporter: "java-junit"

  # ---------- SONAR FRONT : consomme l'artifact de couverture ----------
  sonar-front:
    name: SonarCloud - Front
    runs-on: ubuntu-latest
    needs: [front-tests]
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      # Restaure l'artifact à la RACINE pour conserver les chemins originaux
      - name: Download coverage (Front)
        uses: actions/download-artifact@v4
        with:
          name: coverage-front
          path: .

      # Recherche robuste + normalisation vers un chemin stable
      - name: Normalize & check LCOV
        run: |
          set -e
          LCOV="$(find . -path './front/coverage/*/lcov.info' -o -path './coverage/*/lcov.info' | head -n1 || true)"
          if [ -z "$LCOV" ]; then
            echo "::error::lcov.info introuvable"; ls -R front/coverage || true; exit 1
          fi
          mkdir -p front/coverage/sonar
          cp "$LCOV" front/coverage/sonar/lcov.info
          head -n 5 front/coverage/sonar/lcov.info

      - name: SonarCloud scan (front)
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: front
          args: >
            -Dsonar.projectKey=a-pogam_Gerez-un-projet-collaboratif-en-int-grant-une-demarche-CI-CD_front
            -Dsonar.organization=a-pogam
            -Dsonar.javascript.lcov.reportPaths=coverage/sonar/lcov.info
            -Dsonar.qualitygate.wait=true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io

  # ---------- SONAR BACK : consomme l'artifact JaCoCo ----------
  sonar-back:
    name: SonarCloud - Back
    runs-on: ubuntu-latest
    needs: [back-tests]
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      # Rebuild (no tests) pour avoir target/classes
      - name: Build back (no tests)
        working-directory: back
        run: mvn -B -DskipTests package

      # Restaure l'artifact à la RACINE pour conserver les chemins originaux
      - name: Download coverage (Back)
        uses: actions/download-artifact@v4
        with:
          name: coverage-back
          path: .

      # Recherche robuste + normalisation vers un chemin stable
      - name: Normalize & check JaCoCo XML
        run: |
          set -e
          XML="$(find . -path './back/target/site/jacoco/jacoco.xml' -o -path './**/site/jacoco/jacoco.xml' | head -n1 || true)"
          if [ -z "$XML" ]; then
            echo "::error::jacoco.xml introuvable"; ls -R back/target/site || true; exit 1
          fi
          mkdir -p back/target/site/jacoco
          cp "$XML" back/target/site/jacoco/jacoco.xml
          sed -n '1,5p' back/target/site/jacoco/jacoco.xml

      - name: SonarCloud scan (back)
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: back
          args: >
            -Dsonar.projectKey=a-pogam_Gerez-un-projet-collaboratif-en-int-grant-une-demarche-CI-CD_back
            -Dsonar.organization=a-pogam
            -Dsonar.java.binaries=target/classes
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
            -Dsonar.qualitygate.wait=true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_BACK }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io

  # ---------- DOCKER (main only) ----------
  docker-publish-front:
    name: Docker Publish - FRONT
    runs-on: ubuntu-latest
    needs: [report-tests, sonar-front]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository_owner == 'A-Pogam'
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & push (front)
        uses: docker/build-push-action@v6
        with:
          context: ./front
          file: ./front/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-front:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-front:main
            ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-front:${{ github.sha }}

  docker-publish-back:
    name: Docker Publish - BACK
    runs-on: ubuntu-latest
    needs: [report-tests, sonar-back]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository_owner == 'A-Pogam'
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & push (back)
        uses: docker/build-push-action@v6
        with:
          context: ./back
          file: ./back/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-back:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-back:main
            ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-back:${{ github.sha }}
