name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  front:
    name: Front-end CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "front/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Setup Chrome
        id: setup-chrome
        uses: browser-actions/setup-chrome@v1

      - name: Export CHROME_BIN
        run: echo "CHROME_BIN=${{ steps.setup-chrome.outputs.chrome-path }}" >> $GITHUB_ENV

      - name: Build
        run: npm run build --if-present

      - name: Test (headless, CI-safe)
        run: npm test -- --watch=false --browsers=ChromeHeadlessCI

  back:
    name: Back-end CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Maven verify (tests inclus)
        run: mvn -B clean verify
